### ISSUE TITLE
Choose album art from local images without internet

### ISSUE THREAD

**Issue by AlanSmythe** [vanilla-music/vanilla-music-cover-fetch#16]
Hello,

I was wondering if it was possible to modify this plugin so we can use it to select album art even if we do not have internet access via local photos from our personal device galleries. I find if I try to use it, it has to check for album art on internet first before it will allow me to select my own local photo, and I was wondering if you could make it so we can choose which one we want.

**Comment by Kaned1as** [comment]
Well it has "pick local image" option, hit "pen" button in the header. Does than answer your question?

**Comment by AlanSmythe** [comment]
> Well it has "pick local image" option, hit "pen" button in the header. Does than answer your question?

No because that option will only appear once ir connecta to internet. I want to option to do that without any connection.

**Comment by SebiderSushi** [comment]
Immediately showing the pen or "Pick local image file" button will also be useful if you are on a slow internet connection (e.g. throttled mobile network).

But yeah, if completely offline, the pen and local files button would never appear at all.

**Comment by SebiderSushi** [comment]
The upgrade finally made its way to F-Droid some days ago, thank you very much 👍

**Comment by AlanSmythe** [comment]
Yes, thank you, I appreciate your work on this.

**Comment by SebiderSushi** [comment]
I tried to use the current ersion now for a bit and found two new issues, i'm not sure if they should be sorted into new issues here on github since they are related to this change.

1 - If i press the circled arrow button to fetch a new cover image for an audio file that already has one saved locally, this crash happens: https://del.dog/exycuroppa

2 - Previously, the cover image plugin immediately displayed a local image if present. When off-line, the sad cloud image overrides that while the previous behavior remains when connected to the internet. This seemed unintended so i thought i'd mention it.

**Comment by SebiderSushi** [comment]
Number one now also happened on files without a cover.
Some other files however (with or without local cover) did not produce the crash.

It seems like it could be tied to individual file metadata / cover search results.

**Comment by Kaned1as** [comment]
Crash should be fixed on last version, can you try that? Or was it on the latest (1.4.9)?

**Comment by Kaned1as** [comment]
I will check on the 2nd issue

**Comment by SebiderSushi** [comment]
Ah, sorry i did't realize. I was still on version 1.4.8 since i'm getting the apk from F-Droid.

Checked with your github release apk again and that crash is fixed just fine :+1:
Also i cannot reproduce the offline issue anymore? Soo...i don't know where that came from.

All in all thank you again for your fix and sorry for wasting any time.
